import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#3d2424e0',
    paddingBottom: 40,
  },
  containerSpaceB: {
    justifyContent: 'center',
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginTop: 20,
    gap: 50,
  },
  containerBuyGems: {
    marginTop: 50,
    justifyContent: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 20,
  },
  containerChest: {
    backgroundColor: '#202020',
    borderWidth: 2,
    borderColor: '#848484',
    alignItems: 'center',
    paddingTop: 10,
    gap: 10,
    borderRadius: 5,
    padding: 6,
  },
  textTypeChest: {
    color: 'whitesmoke',
    fontSize: 15,
  },
  containerBuyGemsCard: {
    backgroundColor: '#202020',
    minWidth: 100,
    borderWidth: 1,
    borderColor: '#848484',
    alignItems: 'center',
    gap: 2,
    borderRadius: 5,
    padding: 3,
    paddingVertical: 10,
  },
  imageChest: {
    width: 70,
    height: 70,
  },
  imageGems: {
    width: 40,
    height: 40,
  },
  openChestButton: {
    width: 100,
    borderWidth: 2,
    borderColor: '#848484',
    borderRadius: 5,
    paddingVertical: 6,
    backgroundColor: '#727272',
  },
  openChestText: {
    textAlign: 'center',
    fontWeight: 'bold',
  },
  buyGemText: {
    textAlign: 'center',
    fontWeight: 'bold',
    color: '#848484',
  },
  containerFormAcess2: {
    position: 'absolute',
    backgroundColor: '#594875',
    borderRadius: 50,
    paddingVertical: 8,
    width: '100%',
    alignSelf: 'center',
    bottom: '25%',
    alignItems: 'center',
  },
  containerFormAcessText: {
    fontSize: 24,
    color: '#ffffff',
    fontWeight: 'bold',
  },
  container2: {
    marginTop: 350,
    flex: 0.2,
    backgroundColor: '#0c8b1f',
  },
  container3: {
    marginTop: 40,
    flex: 0.2,
    backgroundColor: '#140c8b',
  },
  containerFormAcess: {
    position: 'absolute',
    backgroundColor: '#594875',
    borderRadius: 50,
    paddingVertical: 8,
    width: '100%',
    alignSelf: 'center',
    bottom: '25%',
    alignItems: 'center',
  },
  containerChestCharacter: {
    alignSelf: 'center',
    marginTop: 20,
    backgroundColor: '#202020',
    borderWidth: 2,
    borderColor: '#848484',
    alignItems: 'center',
    paddingTop: 10,
    gap: 10,
    borderRadius: 5,
    padding: 6,
  },
  imageChestCharacter: {
    width: 120,
    height: 120,
    resizeMode: 'contain',
  },
  openChestCharacterButton: {
    width: 140,
    borderWidth: 2,
    borderColor: '#848484',
    borderRadius: 5,
    paddingVertical: 6,
    backgroundColor: '#727272',
  },
  openChestCharacterText: {
    fontSize: 18,
    textAlign: 'center',
    fontWeight: 'bold',
  },
});
