import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#3d2424e0',
  },
  containerSpaceB: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginTop: 20,
  },
  containerItem: {
    backgroundColor: '#727272',
    alignSelf: 'flex-start',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    borderWidth: 2,
    borderColor: '#fff',
    borderRadius: 8,
    height: 60,
    width: 60,
  },
  containerCharactersChoice: {
    backgroundColor: 'black',
    flex: 1,
    width: 150,
    margin: 10,
    padding: 15,
  },
  containerCharacter: {
    flex: 1,
  },
  characterImage: {
    width: 200,
    height: 215,
    resizeMode: 'contain',
  },
  textChoiceTitle: {
    color: 'white',
    flex: 1,
    fontSize: 16,
    textAlign: 'center',
  },
  containerChoiceButtons: {
    // flexDirection: "row",
    gap: 10,
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
  },
  containerChoiceButton: {
    backgroundColor: 'red',
    padding: 4,
  },
  textChoiceButton: {
    color: 'white',
  },
  containerInventoryItens: {
    backgroundColor: '#202020',
    marginTop: 20,
    flex: 2,
    paddingVertical: 20,
    borderWidth: 2,
    marginHorizontal: 20,
    marginBottom: 20,
  },
  containerScrollViewItens: {
    backgroundColor: '#202020',
    flex: 1,
    // marginTop: 20,
  },
  containerItensChest: {
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 13,
  },
  imageItemDefault: {
    width: 50,
    height: 50,
    resizeMode: 'contain',
  },
  container2: {
    flex: 0.1,
    backgroundColor: '#0c8b1f',
    marginTop: 25,
  },
  container3: {
    flex: 0.1,
    backgroundColor: '#140c8b',
  },
  containerFormAcess: {
    position: 'absolute',
    backgroundColor: '#594875',
    borderRadius: 50,
    paddingVertical: 8,
    width: '100%',
    alignSelf: 'center',
    bottom: '25%',
    alignItems: 'center',
  },
  containerFormAcess2: {
    position: 'absolute',
    backgroundColor: '#594875',
    borderRadius: 50,
    paddingVertical: 8,
    width: '100%',
    alignSelf: 'center',
    bottom: '25%',
    alignItems: 'center',
  },
  containerFormAcessText: {
    fontSize: 24,
    color: '#ffffff',
    fontWeight: 'bold',
  },
  containerStats: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginTop: 5,
    alignItems: 'center',
  },
  buttonCharacter: {
    backgroundColor: '#2B2B2B',
    padding: 4,
    borderRadius: 4,
    marginLeft: -5,
    borderWidth: 1,
    borderColor: 'grey',
  },
  buttonCharacterText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  statsText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: 'bold',
    backgroundColor: 'black',
    padding: 6,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'grey',
  },
});
